### ISSUE TITLE
failed to open library - ./libdmlab.so

### ISSUE THREAD

**Issue by sygi** [miyosuda/unreal#12]
I tried running `unreal:train --define headless=osmesa`, but got the following error.
```
Failed to open library! - ./libdmlab.so
dlopen: cannot load any more object with static TLS
Process Process-1:
Traceback (most recent call last):
  File "/part/01/Tmp/lisa/os_v5/anaconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/part/01/Tmp/lisa/os_v5/anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data/lisa/exp/sygnowsj/lab/unreal/environment/lab_environment.py", line 26, in worker
    'height': str(84)
RuntimeError: Failed to connect RL API
```
Do you know why it happens? (the libdmlab.so library is there in bazel-bin)

**Comment by sygi** [comment]
It turned out it was a bigger problem with the lab, that was resolved by recompiling mesa with different flags. Closing now.
